server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SawanPanwar/Spring-Cloud-Config.git
          clone-on-start: true